apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: kristoffer77/my-app-image:master-5ef154ce9dd5b09a97c0ecc8bfa54b3f933130df
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
