apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: kristoffer77/my-app-image:master-537ace185b77b8551e244558c98a9abd0cf08bd8
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
